### PR TITLE
Component schema

### PR DESCRIPTION
**Pull request by jasollien**

### CODE REVIEW

**Comment by GeorgDangl** [comment]
I think by directly referencing the `component_list` in (for example) `component_GET`:

    "components": {
        "$ref": "component_list.json"
    },

you'd get an instance like this:

    {
        "components": {
            "components": [
                ...
            ]
        }
    }

You could omit the `component_list` and only reference the `component` directly, like this (for `component_GET`):

    {
        "$schema": "http://json-schema.org/draft-03/schema#",
        "title": "component_GET",
        "description": "Schema for components GET, BCF REST API.",
        "type": "object",
        "components": {
            "type": ["array", "null"],
            "items": {
                "$ref": "component.json"
            }
        },
        "spaces": {
            "type": ["array", "null"],
            "items": {
                "$ref": "component.json"
            }
        },
        "spaceBoundaries": {
            "type": ["array", "null"],
            "items": {
                "$ref": "component.json"
            }
        },
        "openings": {
            "type": ["array", "null"],
            "items": {
                "$ref": "component.json"
            }
        }
    }

**Comment by jasollien** [comment]
Sounds good

**Comment by jasollien** [comment]
@GeorgDangl. In your example, the DefaultVisibility is omitted? Do you know if it's possible to add that attribute directlly inside components, spaces, ... ?

**Comment by jasollien** [comment]
JSON is a bit different to xml. We could make the output like this:

{
	"components": {
        items: 
      	[
          {
            "ifc_guid": "",
            "selected": true,
            "visible": true,
          	"color": "red",
          	"originating_system": "bimsync",
          	"authoring_tool_id": null
         
          }
        ],
        defaultVisibility: true
    }
}

In that case, I will keep the component_list.json, but rename "components" to "items"

**Comment by GeorgDangl** [comment]
Yeah, that last example of you sounds like the way to go!

**Comment by jasollien** [comment]
Great. It is updated now. Will start writing the documentation now

**Comment by GeorgDangl** [comment]
Looks good from my point of view, merging & closing this

**Pull request merged**
