### PR TITLE
Identifying guids

### PR DESCRIPTION
**Pull request by vjleo**
Hi there,
I've located some inconsistencies on the paths.

project id as : {project_id}, but also as {guid}

It's not good practice to have the same parameter in the URL.

its better to define what guid is it relative to.

Regards,
Leo

### CODE REVIEW

**Review by jasollien — APPROVED** [review]

**Comment by ykulbak** [comment]
Should this be merged into `master` rather than the release branch?

**Comment by GeorgDangl** [comment]
Yeh, that should target the master branch, please😀

**Comment by GeorgDangl** [comment]
I'll need to recreate the PR with only the actual commit that's fixing the issue.

**Comment by GeorgDangl** [comment]
Done via #314

**Pull request closed without merging**
