### PR TITLE
added CC license

### PR DESCRIPTION
**Pull request by berlotti**

### CODE REVIEW

**Comment by GeorgDangl** [comment]
Should we also include a License file? That way, it’s easier to quickly see and identify the license in the repository.

**Comment by thbeu** [comment]
> Should we also include a License file? That way, it’s easier to quickly see and identify the license in the repository.

Yes, this would be very useful. See https://github.com/modelica/ModelicaSpecification/blob/master/LICENSE.md for an idea how it can be done.

In other word: Is the licence CC BY-ND 4.0 instead of the proposed CC BY-NC-SA 4.0 ❔ Just wondering... 😕

**Comment by berlotti** [comment]
It is  Creative Commons Attribution-NoDerivatives 4.0 International License. 
http://creativecommons.org/licenses/by-nd/4.0/ 

I just created a pull request for a license file

**Comment by thbeu** [comment]
> I just created a pull request for a license file

Yould have also updated this PR instead of creating a new PR. Anyway...

**Pull request closed without merging**
